import type { Metadata } from "next";
import "./globals.css";
import { Comforter } from "next/font/google";

const comforter = Comforter({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    team,
    analytics,
}: Readonly<{
    children: React.ReactNode;
    team: React.ReactNode;
    analytics: React.ReactNode;
}>) {
    return (
        <html lang="zh">
            <body className={comforter.className}>
                <div>
                    {team}
                    {analytics}
                </div>
                {children}
            </body>
        </html>
    );
}
