import type { Metadata } from "next";
import "./globals.css";
import { Comforter } from "next/font/google";

const comforter = Comforter({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    modal,
}: Readonly<{
    children: React.ReactNode;
    modal: React.ReactNode;
}>) {
    return (
        <html lang="zh">
            <body className={comforter.className}>
                {children}
                {modal}
            </body>
        </html>
    );
}
